<a href="https://colab.research.google.com/github/shivampatle2004/python_pratice/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

# Example of a 3D array
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]],[[9,10],[11,12]]])
print("This is a 3D array (b):\n", b)
print("Dimensions of b:", b.ndim)
print("Shape of b:", b.shape)

This is a 3D array (b):
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Dimensions of b: 3
Shape of b: (3, 2, 2)


In [5]:
a=np.array([[1,2],[3,4],[5,6]])
print(a)
print("Dimensions of a:", a.ndim)

[[1 2]
 [3 4]
 [5 6]]
Dimensions of a: 2


In [9]:
a=np.array([1,2,3],dtype=float)#int by deafult and booen and string
b=np.array([1,2,3],dtype=str)
print(a,b)

[1. 2. 3.] ['1' '2' '3']


In [19]:
a=np.arange(1,11)
print(a)
for i in a:
  print(i*2)

[ 1  2  3  4  5  6  7  8  9 10]
2
4
6
8
10
12
14
16
18
20


In [22]:
#reshape only if possible
a=np.arange(1,11).reshape(2,5)#all possible multipal of 10 .
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [27]:
c=np.ones((1,2))
print(c)


[[1. 1.]]


In [29]:
d=np.zeros((3))
print(d)

[0. 0. 0.]


In [32]:
d=np.random.random((1,2))
print(d)

[[0.33442008 0.97509499]]


In [46]:
np.linspace(1,2,3,dtype=int)#equal distribution
c=np.linspace(1,2,3,dtype=int)
print(c)

[1 1 2]


In [38]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])